manipulator_description:  

  # Position Controllers ---------------------------------------
  joint_1_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_1
    pid: { p: 5000.0, i: 0.0, d: 10}
  joint_2_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_2
    pid: { p: 5000.0, i: 0.0, d: 10}
  joint_3_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_3
    pid: { p: 5000.0, i: 0.0, d: 10}
  joint_4_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_4
    pid: { p: 5000.0, i: 0.0, d: 10}
  joint_5_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_5
    pid: { p: 5000.0, i: 0.0, d: 10}
  joint_6_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_6
    pid: { p: 5000.0, i: 0.0, d: 10}
