manipulator_description:
   # Publish all joint states -----------------------------------
#  joint_state_controller:
#    type: "joint_state_controller/JointStateController"
#    publish_rate: 50 

  arm_controller:
    type: "velocity_controllers/JointTrajectoryController"
    joints:
       - joint_1
       - joint_2
       - joint_3
       - joint_4
       - joint_5
       - joint_6
 
    constraints:
        goal_time: 0
        stopped_velocity_tolerance: 0.0
        joint_1: {trajectory: 0, goal: 0}
        joint_2: {trajectory: 0, goal: 0}
        joint_3: {trajectory: 0, goal: 0}
        joint_4: {trajectory: 0, goal: 0}
        joint_5: {trajectory: 0, goal: 0}
        joint_6: {trajectory: 0, goal: 0}
    stop_trajectory_duration: 1.0
    state_publish_rate:  50
    action_monitor_rate: 20


# manipulator_description/gazebo_ros_control/pid_gains:
    gains:
        joint_1:   {p: 5000.0, i: 0.0, d: 10, i_clamp: 0.0}
        joint_2:   {p: 5000.0, i: 0.0, d: 10, i_clamp: 0.0}
        joint_3:   {p: 5000.0, i: 0.0, d: 10, i_clamp: 0.0}
        joint_4:   {p: 5000.0, i: 0.0, d: 10, i_clamp: 0.0}
        joint_5:   {p: 3000.0, i: 0.0, d: 100, i_clamp: 0.0}
        joint_6:   {p: 5000.0, i: 0.0, d: 10, i_clamp: 0.0}
        push_joint: {p: 5000.0, i: 0.0, d: 10, i_clamp: 0.0}

manipulator_description/gazebo_ros_control/pid_gains:
        joint_1:   {p: 5000.0, i: 0.0, d: 10, i_clamp: 0.0}
        joint_2:   {p: 5000.0, i: 0.0, d: 10, i_clamp: 0.0}
        joint_3:   {p: 5000.0, i: 0.0, d: 10, i_clamp: 0.0}
        joint_4:   {p: 5000.0, i: 0.0, d: 10, i_clamp: 0.0}
        joint_5:   {p: 3000.0, i: 0.0, d: 100, i_clamp: 0.0}
        joint_6:   {p: 5000.0, i: 0.0, d: 10, i_clamp: 0.0}
        push_joint: {p: 5000.0, i: 0.0, d: 10, i_clamp: 0.0}

