manipulator_description:
# MoveIt-specific simulation settings
  moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
#  generic_hw_control_loop:
#    loop_hz: 300
#    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
# hardware_interface:
#    joints:
#      - joint_1
#      - joint_2
#      - joint_3
#      - joint_4
#      - joint_5
#      - joint_6
#      - push_joint
#      - joint_6
#    constraints:
#      goal_time: 0.6
#      stopped_velocity_tolerance: 0.05
#      joint_1: {trajectory: 0.1, goal: 0.1}
#      joint_2: {trajectory: 0.1, goal: 0.1}
#      joint_3: {trajectory: 0.1, goal: 0.1}
#      joint_4: {trajectory: 0.1, goal: 0.1}
#      joint_5: {trajectory: 0.1, goal: 0.1}
#      joint_6: {trajectory: 0.1, goal: 0.1}
#    stop_trajectory_duration: 0.5
#    state_publish_rate:  25
#    action_monitor_rate: 10

